[phases.setup]
nixPkgs = ["openssl", "openssl.dev", "chromium", "glib", "nss", "nspr", "atk", "at-spi2-atk", "cups", "dbus", "expat", "libdrm", "libxkbcommon", "mesa"]
 
[phases.build]
cmds = ["npm install", "npx prisma generate", "npx playwright install chromium --with-deps", "npm run build"]
 
[start]
cmd = "node dist/index.js"
 